apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps-predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aps-predictor
  template:
    metadata:
      labels:
        app: aps-predictor
    spec:
      containers:
      - name: aps-predictor
        image: aps-predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
